# Definição das variáveis globais
ESCALA_PERSONAGEM = 0.4
ESCALA_INIMIGO = 0.4
ESCALA_MOEDA = 1
ESCALA_SACO = 1
ESCALA_MALETA = 1
ESCALA_PLATAFORMA = 1
ESCALA_CHAO_TETO = 1
TEMPO_DROP = 3
TEMPO_INIMIGO = 10

LARGURA_TELA = 900
ALTURA_TELA = 660
TITULO = "Russian Race"

VELOCIDADE_CIMA = 9
VELOCIDADE_CIMA_INIMIGO = 9
MOVIMENTO_LADO_PERSONAGEM = 3